apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ticketing
build:
  # local:
  #   push: false
  artifacts: #setup code syncing
    - image: maria12/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: # this sync any change in file in below src path to pod
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: maria12/next-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: # this sync any change in file in below src path to pod
        manual:
          - src: '**/*.ts'
            dest: .
    - image: maria12/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: # this sync any change in file in below src path to pod
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/auth-mongo.depl.yaml
    - infra/k8s/next-client-depl.yaml
    - infra/k8s/tickets-depl.yaml
    #- infra/k8s/nats-depl.yaml